#!/usr/bin/env python3
"""Generate an assembly translation unit embedding the pinned UI fonts."""

from __future__ import annotations

import argparse
from pathlib import Path


def q(path: Path) -> str:
    # GNU as accepts C-style quoted strings. Build inputs live in the WSL cache;
    # escape backslashes and quotes defensively.
    return str(path.resolve()).replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("regular", type=Path)
    parser.add_argument("bold", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    for path in (args.regular, args.bold):
        if not path.is_file() or path.stat().st_size < 1024:
            raise RuntimeError(f"invalid font input: {path}")

    text = f'''/* Generated by scripts/prepare-font-embed.py. */
.section .rodata
.balign 16
.global rp_font_regular
rp_font_regular:
.incbin "{q(args.regular)}"
.global rp_font_regular_end
rp_font_regular_end:
.balign 16
.global rp_font_bold
rp_font_bold:
.incbin "{q(args.bold)}"
.global rp_font_bold_end
rp_font_bold_end:
.section .note.GNU-stack,"",@progbits
'''
    args.output.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
